Don't hardcode sending TL1's first post to akismet
discourse/discourse-akismet pull request #51
Opened 2022-03-25 14:54 UTC by mbauman

As highlighted by [this comment on discourse meta](https://meta.discourse.org/t/akismet-filter-misses-so-frequently-how-to-disable-improve/215935/2?u=mbauman), mandating a check on TL1's first post is quite counterintuitive.  This simply removes that, leaning instead entirely on the trust level and post count site settings.

2022-03-25 18:26 UTC, romanrizzi requested changes
Thanks for taking the time to submit this PR, @mbauman!

I understand it may seem counterintuitive because we don't check posts from TL1+ users by default. However, it's important to keep this check because TL1 is the only level that doesn't require you to visit multiple days:

```
Get to trust level 1 by…
Entering at least 5 topics
Reading at least 30 posts
Spend a total of 10 minutes reading posts
```

Technically, a spammer could bypass the plugin by visiting topics and "reading" posts for 10 minutes before posting.

Instead of removing the check, we could:

- Skip the check when`skip_akismet_trust_level`is 0.
- Update the comment to clarify why we need the check.  

What do you think?

2022-03-25 20:08 UTC, mbauman commented
I'm ok doing that, but goodness the logic and motivation here seems quite confused.  We have settings for:

* Skip checks on TLX and above, defaulting to 1
* Skip checks on users with X posts and above, defaulting to 50

And then hardcoded and invisible to admins:
* Ensure TL1's first post is checked

My motivation here is that akismet has proved to be worthless on our hosted site... but as a hosted site we cannot disable the plugin.  It appears as though setting skip_aksimet_trust_level to 0 would disable things, and with this patch that now does indeed work.

2022-03-28 20:27 UTC, romanrizzi commented
Yes, you're right about that. I think it's better to make it configurable with a site setting then. See #52

> My motivation here is that akismet has proved to be worthless on our hosted site... 

I'll take a look and see if there's something we can change on our side to make the plugin more effective.

2022-03-28 22:22 UTC, mbauman commented
Thanks! #52 accomplishes my end goal here, so we can close this.

As an aside, I often find toggles and switches much more intuitive if they name the _positive_ action instead of the negative one.  In other words, _enable_ checks for some category of user, instead of skipping them for the inverse.

> I'll take a look and see if there's something we can change on our side to make the plugin more effective.

I'm happy to provide a handful of false positives from our site if that'd be helpful.

2022-03-28 22:22 UTC, closed without merging